config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end


  def show
  end


  def new
    @article = Article.new
  end


  def create
    @article = Article.create!(article_params)
    redirect_to articles_path(@articles)
  end


  def edit
  end


  def update
    @article.update(article_params)
    redirect_to articles_path(@articles)
  end


  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>
  <p><%= f.label :content %></p>
  <p><%= f.text_area :content %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/articles/edit.html.erb
<div class="header">
  <h1 class="title text-center">Update Your Article</h1>
</div>

<div class="wraper text-center">
  <%= render "form" %>
</div>

<p class="text-center"><%= link_to "Cancel", articles_path(@articles), class: "btn btn-primary" %></p>

app/views/articles/index.html.erb
<div class="header">
  <h1 class="title text-center">What's new in Wikinimous</h1>
</div>

<div class="wraper">
  <div class="container">
    <div class="row ">
    <ul>
      <% @articles.each do |article| %>
      <li class="article">
          <h2><%= link_to article.title, article_path(article) %></h2>
          <p><%= raw Kramdown::Document.new(article.content).to_html %> Created : <%= article.created_at%>
          <%= link_to "See more" , article_path(article)%></p>
          <div class="text-center">
            <ul class="list-inline">
              <li><%= link_to "UPDATE", edit_article_path(article), class: "btn btn-primary"%></li>
              <li><%= link_to "DELETE", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary"%></li>
            </ul>
          </div>
      </li>
      <% end %>
    </ul>
    </div>

  </div>
</div>

<div class="footer text-center">
<%= link_to "Write an article", new_article_path(@article), class:"footer btn btn-primary" %>
</div>

app/views/articles/new.html.erb
<div class="header">
  <h1 class="title text-center">Write your new article</h1>
</div>

<div class="wraper text-center">
  <%= render "form" %>
</div>

<p class="text-center"><%= link_to "Cancel", articles_path(@articles), class: "btn btn-primary"%></p>

app/views/articles/show.html.erb
<div class="header">
  <h1 class="title text-center">Here is your article</h1>
</div>

<div class="wraper text-center">
    <h1><%= @article.title %></h1>

    <p><%= @article.content %></p>
</div>

<div class="text-center">
  <%= link_to "Back to articles", articles_path(@articles), class: "footer btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>